import json
from typing import AsyncGenerator, List, Optional
from fastapi import APIRouter, Depends, HTTPException, Request, status
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from app.api.deps import get_current_user, get_db, get_optional_user
from app.core.config import settings
from app.models.chat import ChatMessageRecord, Conversation
from app.models.user import User
from app.schemas.chat import ChatRequest, ChatResponse, ConversationRead

router = APIRouter()

SYSTEM_INSTRUCTION = (
    "You are Aivora, a high-performance desktop AI assistant. "
    "Provide clear, concise, intelligent, and beautifully structured responses with Markdown formatting."
)


async def stream_gemini_response(prompt: str, history: Optional[List[dict]] = None) -> AsyncGenerator[str, None]:
    """Streams token generations using the official Google Gemini SDK."""
    api_key = settings.GEMINI_API_KEY
    if not api_key:
        yield "Error: GEMINI_API_KEY is not configured on the backend server."
        return

    # 1. Primary: Official google-genai SDK
    try:
        from google import genai
        from google.genai import types

        client = genai.Client(api_key=api_key)

        contents = []
        if history:
            for msg in history:
                role = "user" if msg.get("sender") == "user" else "model"
                contents.append(
                    types.Content(
                        role=role,
                        parts=[types.Part.from_text(text=msg.get("text", ""))],
                    )
                )
        contents.append(
            types.Content(
                role="user",
                parts=[types.Part.from_text(text=prompt)],
            )
        )

        config = types.GenerateContentConfig(
            system_instruction=SYSTEM_INSTRUCTION,
            temperature=0.7,
            max_output_tokens=2048,
        )

        response_stream = await client.aio.models.generate_content_stream(
            model="gemini-3.5-flash-lite",
            contents=contents,
            config=config,
        )
        async for chunk in response_stream:
            token = chunk.text if chunk and chunk.text else ""
            if token:
                yield token
        return

    except ImportError:
        pass
    except Exception as exc:
        yield f"\n[Gemini Error: {str(exc)}]"
        return

    # 2. Fallback: Legacy google-generativeai SDK if user already has it
    try:
        import google.generativeai as legacy_genai

        legacy_genai.configure(api_key=api_key)
        model = legacy_genai.GenerativeModel(
            model_name="gemini-3.5-flash-lite",
            system_instruction=SYSTEM_INSTRUCTION,
        )
        chat_contents = []
        if history:
            for msg in history:
                role = "user" if msg.get("sender") == "user" else "model"
                chat_contents.append({"role": role, "parts": [msg.get("text", "")]})
        chat_contents.append({"role": "user", "parts": [prompt]})

        response_stream = await model.generate_content_async(chat_contents, stream=True)
        async for chunk in response_stream:
            token = chunk.text if chunk and chunk.text else ""
            if token:
                yield token
        return

    except Exception as exc:
        yield f"\n[Gemini Error: {str(exc)}]"
        return


async def generate_gemini_response(prompt: str, history: Optional[List[dict]] = None) -> str:
    """Generates an answer using the official Google Gemini Python library."""
    tokens = []
    async for token in stream_gemini_response(prompt, history=history):
        tokens.append(token)
    return "".join(tokens) or "No response text generated by Gemini."


@router.post("", summary="Send message to AI Assistant")
async def send_chat_message(
    chat_req: ChatRequest,
    request: Request,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Processes an AI assistant question directly using Gemini with real-time SSE token streaming."""
    conv_id = chat_req.conversation_id
    history_messages = []

    # If conversation exists for this authenticated user, load context
    if current_user and conv_id:
        existing_conv = (
            db.query(Conversation)
            .filter(Conversation.id == conv_id, Conversation.user_id == current_user.id)
            .first()
        )
        if existing_conv:
            prev_records = (
                db.query(ChatMessageRecord)
                .filter(ChatMessageRecord.conversation_id == conv_id)
                .order_by(ChatMessageRecord.created_at.asc())
                .limit(8)
                .all()
            )
            history_messages = [{"sender": r.sender, "text": r.text} for r in prev_records]

    # Persist conversation and user message up front
    if current_user:
        if conv_id:
            conv = (
                db.query(Conversation)
                .filter(Conversation.id == conv_id, Conversation.user_id == current_user.id)
                .first()
            )
        else:
            conv = None

        if not conv:
            # Create a title based on first 40 chars of question
            title = chat_req.question.strip()[:40] or "New Chat"
            conv = Conversation(user_id=current_user.id, title=title)
            db.add(conv)
            db.commit()
            db.refresh(conv)

        conv_id = conv.id
        user_msg = ChatMessageRecord(conversation_id=conv.id, sender="user", text=chat_req.question)
        db.add(user_msg)
        db.commit()

    # Determine if client requested SSE streaming
    accept_header = request.headers.get("accept", "").lower()
    wants_streaming = (chat_req.stream is not False) or ("text/event-stream" in accept_header)

    if wants_streaming:
        async def event_generator():
            accumulated_tokens = []
            try:
                # Initial event to emit conversation_id immediately
                init_data = json.dumps({"token": "", "conversation_id": conv_id, "done": False})
                yield f"data: {init_data}\n\n"

                # Stream token generation
                async for token in stream_gemini_response(chat_req.question, history=history_messages):
                    accumulated_tokens.append(token)
                    token_data = json.dumps({"token": token, "conversation_id": conv_id, "done": False})
                    yield f"data: {token_data}\n\n"

                # Record completed assistant message in database
                full_answer = "".join(accumulated_tokens).strip()
                if current_user and conv_id and full_answer:
                    try:
                        assistant_msg = ChatMessageRecord(
                            conversation_id=conv_id,
                            sender="assistant",
                            text=full_answer,
                        )
                        db.add(assistant_msg)
                        db.commit()
                    except Exception:
                        db.rollback()

                # Completion event
                done_data = json.dumps({
                    "token": "",
                    "answer": full_answer,
                    "conversation_id": conv_id,
                    "done": True,
                })
                yield f"data: {done_data}\n\n"

            except Exception as stream_err:
                err_data = json.dumps({
                    "error": str(stream_err),
                    "conversation_id": conv_id,
                    "done": True,
                })
                yield f"data: {err_data}\n\n"

        return StreamingResponse(
            event_generator(),
            media_type="text/event-stream",
            headers={
                "Cache-Control": "no-cache, no-transform",
                "Connection": "keep-alive",
                "X-Accel-Buffering": "no",
                "Content-Type": "text/event-stream; charset=utf-8",
            },
        )

    # Fallback to non-streaming response
    answer = await generate_gemini_response(chat_req.question, history=history_messages)
    if current_user and conv_id:
        assistant_msg = ChatMessageRecord(conversation_id=conv_id, sender="assistant", text=answer)
        db.add(assistant_msg)
        db.commit()

    return ChatResponse(
        question=chat_req.question,
        answer=answer,
        conversation_id=conv_id,
    )


@router.get("/conversations", response_model=List[ConversationRead], summary="List Saved Conversations")
def list_conversations(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> List[ConversationRead]:
    convs = (
        db.query(Conversation)
        .filter(Conversation.user_id == current_user.id)
        .order_by(Conversation.updated_at.desc())
        .all()
    )
    return [ConversationRead.model_validate(c) for c in convs]


@router.get("/conversations/{conversation_id}", response_model=ConversationRead, summary="Get Conversation Messages")
def get_conversation(
    conversation_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> ConversationRead:
    conv = (
        db.query(Conversation)
        .filter(Conversation.id == conversation_id, Conversation.user_id == current_user.id)
        .first()
    )
    if not conv:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Conversation not found")
    return ConversationRead.model_validate(conv)


@router.delete("/conversations/{conversation_id}", summary="Delete Conversation")
def delete_conversation(
    conversation_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> dict:
    conv = (
        db.query(Conversation)
        .filter(Conversation.id == conversation_id, Conversation.user_id == current_user.id)
        .first()
    )
    if not conv:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Conversation not found")
    db.delete(conv)
    db.commit()
    return {"message": "Conversation deleted"}
