from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from app.api.deps import get_current_user, get_db, get_optional_user
from app.core.config import settings
from app.models.chat import ChatMessageRecord, Conversation
from app.models.user import User
from app.schemas.chat import ChatRequest, ChatResponse, ConversationRead

router = APIRouter()

SYSTEM_INSTRUCTION = (
    "You are Aivora, a high-performance desktop AI assistant. "
    "Provide clear, concise, intelligent, and beautifully structured responses with Markdown formatting."
)


async def generate_gemini_response(prompt: str, history: Optional[List[dict]] = None) -> str:
    """Generates an answer using the official Google Gemini Python library."""
    api_key = settings.GEMINI_API_KEY
    if not api_key:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="GEMINI_API_KEY is not configured on the backend server.",
        )

    # 1. Primary: Official google-genai SDK
    try:
        from google import genai
        from google.genai import types

        client = genai.Client(api_key=api_key)

        contents = []
        if history:
            for msg in history:
                role = "user" if msg.get("sender") == "user" else "model"
                contents.append(
                    types.Content(
                        role=role,
                        parts=[types.Part.from_text(text=msg.get("text", ""))],
                    )
                )
        contents.append(
            types.Content(
                role="user",
                parts=[types.Part.from_text(text=prompt)],
            )
        )

        config = types.GenerateContentConfig(
            system_instruction=SYSTEM_INSTRUCTION,
            temperature=0.7,
            max_output_tokens=2048,
        )

        response = await client.aio.models.generate_content(
            model="gemini-3.5-flash-lite",
            contents=contents,
            config=config,
        )
        if response and response.text:
            return response.text
        return "No response text generated by Gemini."

    except ImportError:
        pass
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Gemini library error: {str(exc)}",
        ) from exc

    # 2. Fallback: Legacy google-generativeai SDK if user already has it
    try:
        import google.generativeai as legacy_genai

        legacy_genai.configure(api_key=api_key)
        model = legacy_genai.GenerativeModel(
            model_name="gemini-3.5-flash-lite",
            system_instruction=SYSTEM_INSTRUCTION,
        )
        chat_contents = []
        if history:
            for msg in history:
                role = "user" if msg.get("sender") == "user" else "model"
                chat_contents.append({"role": role, "parts": [msg.get("text", "")]})
        chat_contents.append({"role": "user", "parts": [prompt]})

        response = await model.generate_content_async(chat_contents)
        if response and response.text:
            return response.text
        return "No response text generated by Gemini."

    except ImportError:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Google Gemini Python library not found. Run: pip install google-genai",
        )
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Gemini library error: {str(exc)}",
        ) from exc


@router.post("", response_model=ChatResponse, summary="Send message to AI Assistant")
async def send_chat_message(
    chat_req: ChatRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> ChatResponse:
    """Processes an AI assistant question directly using Gemini 2.5 Flash via FastAPI backend."""
    conv_id = chat_req.conversation_id
    history_messages = []

    # If conversation exists for this authenticated user, load context
    if current_user and conv_id:
        existing_conv = (
            db.query(Conversation)
            .filter(Conversation.id == conv_id, Conversation.user_id == current_user.id)
            .first()
        )
        if existing_conv:
            prev_records = (
                db.query(ChatMessageRecord)
                .filter(ChatMessageRecord.conversation_id == conv_id)
                .order_by(ChatMessageRecord.created_at.asc())
                .limit(8)
                .all()
            )
            history_messages = [{"sender": r.sender, "text": r.text} for r in prev_records]

    # Generate response directly with Google Gemini
    answer = await generate_gemini_response(chat_req.question, history=history_messages)

    # Persist conversation and messages in PostgreSQL
    if current_user:
        if conv_id:
            conv = (
                db.query(Conversation)
                .filter(Conversation.id == conv_id, Conversation.user_id == current_user.id)
                .first()
            )
        else:
            conv = None

        if not conv:
            # Create a title based on first 40 chars of question
            title = chat_req.question.strip()[:40]
            conv = Conversation(user_id=current_user.id, title=title)
            db.add(conv)
            db.commit()
            db.refresh(conv)

        # Record user message and assistant response
        user_msg = ChatMessageRecord(conversation_id=conv.id, sender="user", text=chat_req.question)
        assistant_msg = ChatMessageRecord(conversation_id=conv.id, sender="assistant", text=answer)
        db.add(user_msg)
        db.add(assistant_msg)
        db.commit()
        conv_id = conv.id

    return ChatResponse(
        question=chat_req.question,
        answer=answer,
        conversation_id=conv_id,
    )


@router.get("/conversations", response_model=List[ConversationRead], summary="List Saved Conversations")
def list_conversations(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> List[ConversationRead]:
    convs = (
        db.query(Conversation)
        .filter(Conversation.user_id == current_user.id)
        .order_by(Conversation.updated_at.desc())
        .all()
    )
    return [ConversationRead.model_validate(c) for c in convs]


@router.get("/conversations/{conversation_id}", response_model=ConversationRead, summary="Get Conversation Messages")
def get_conversation(
    conversation_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> ConversationRead:
    conv = (
        db.query(Conversation)
        .filter(Conversation.id == conversation_id, Conversation.user_id == current_user.id)
        .first()
    )
    if not conv:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Conversation not found")
    return ConversationRead.model_validate(conv)


@router.delete("/conversations/{conversation_id}", summary="Delete Conversation")
def delete_conversation(
    conversation_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> dict:
    conv = (
        db.query(Conversation)
        .filter(Conversation.id == conversation_id, Conversation.user_id == current_user.id)
        .first()
    )
    if not conv:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Conversation not found")
    db.delete(conv)
    db.commit()
    return {"message": "Conversation deleted"}
